<?php

namespace Sites\Admin\Zoo\GodparentBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * GiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftRepository extends SortableRepository
{
}
