<?php

namespace Sites\Admin\Zoo\GodparentBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * GiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftRepository extends SortableRepository
{
    public function getLastPosition()
    {
        return $this->createQueryBuilder("g")->select("COUNT(g)")->getQuery()->getSingleScalarResult()-1;
    }
}
