admin_common_mediatek_homepage:
    path:     /
    defaults: { _controller: AdminCommonMediatekBundle:Default:index }

admin_common_mediatek_image_new:
    path: /image/nouvelle
    defaults: { _controller: AdminCommonMediatekBundle:Image:new }

admin_common_mediatek_image_create:
    path: /image/creation
    defaults: { _controller: AdminCommonMediatekBundle:Image:create }
    requirements: { _method: post }

admin_common_mediatek_image_update:
    path: /image/maj/{id}
    defaults: { _controller: AdminCommonMediatekBundle:Image:update }
    requirements: { _method: post, id: \d+ }

admin_common_mediatek_image_delete:
    path: /image/supprimer/{id}
    defaults: { _controller: AdminCommonMediatekBundle:Image:delete }
    requirements:
        id: \d+

admin_common_mediatek_image_edit:
    path: /image/edition/{id}
    defaults: { _controller: AdminCommonMediatekBundle:Image:edit }
    requirements:
        id: \d+

admin_common_mediatek_image_search_by_tagid:
    path: /image/recherche_par_mot_cle/{id}
    defaults: { _controller: AdminCommonMediatekBundle:Image:searchByTagId }
    requirements:
        id: \d+
