<?php

namespace Sites\Admin\Zoo\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZBCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZBCategoryRepository extends EntityRepository
{
}
