<?php

namespace Sites\Admin\Zoo\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZBTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZBTagRepository extends EntityRepository
{
    public function findAllAlphaOrdered()
    {
        $qb = $this->createQueryBuilder("t")->orderBy("t.name", "ASC");
        return $qb->getQuery()->getResult();
    }
}
