parameters:
#    jardins_base.example.class: Sites\Jardins\BaseBundle\Example

services:
#    jardins_base.example:
#        class: %jardins_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
