admin_zoo_blog_post_new:
    path: /rediger
    defaults: { _controller: AdminZooBlogBundle:ZBPost:new }

admin_zoo_blog_post_create:
    path: /creation
    defaults: { _controller: AdminZooBlogBundle:ZBPost:create }
    requirements: { _method: post }

admin_zoo_blog_post_edit:
    path: /edition/{id}
    defaults: { _controller: AdminZooBlogBundle:ZBPost:edit }
    requirements:
        id: \d+
