<?php

namespace Sites\Admin\Zoo\FototekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZFCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZFCategoryRepository extends EntityRepository
{
}
