<?php

namespace Sites\Admin\Zoo\FototekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZFImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZFImageRepository extends EntityRepository
{
    public function getAllByCategory($id)
    {
        $query = $this->_em->createQuery("SELECT i FROM AdminZooFototekBundle:ZFImage i JOIN i.category c WHERE c.id=:id ORDER BY i.position ASC");
        $query->setParameter('id', $id);
        return $query->getResult();
    }

    public function getMaxPosition($id)
    {
        $query = $this->_em->createQuery("SELECT MAX(i.position) AS maxi FROM AdminZooFototekBundle:ZFImage i JOIN i.category c WHERE  c.id=:id");
        $query->setParameter('id', $id);
        return $query->getSingleScalarResult();
    }

    public function moveDownImagesGroup($start, $finish, $id)
    {
        $stmt = $this->_em->getConnection()->prepare("UPDATE zoo_fototek_images SET position = position+1 WHERE category_id=:id AND position>=:start AND position<:finish");
        $stmt->bindValue(":id", $id);
        $stmt->bindValue(":start", $start);
        $stmt->bindValue(":finish", $finish);
        $stmt->execute();
    }

    public function moveUpImagesGroup($start, $finish, $id)
    {
        $stmt = $this->_em->getConnection()->prepare("UPDATE zoo_fototek_images AS z SET z.position = z.position-1 WHERE z.category_id=:id AND z.position>:start AND z.position<=:finish");
        $stmt->bindValue(":id", $id);
        $stmt->bindValue(":start", $start);
        $stmt->bindValue(":finish", $finish);
        $stmt->execute();

    }
}
