admin_zoo_fototek_category_homepage:
    path:     /
    defaults: { _controller: AdminZooFototekBundle:Category:index }

admin_zoo_fototek_category_new:
    path:     /nouvelle
    defaults: { _controller: AdminZooFototekBundle:Category:new }

admin_zoo_fototek_category_create:
    path:     /creation
    defaults: { _controller: AdminZooFototekBundle:Category:create }
    requirements: { _method: post }
