parameters:
#    hotels_base.example.class: Sites\Hotels\BaseBundle\Example

services:
#    hotels_base.example:
#        class: %hotels_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
