parameters:
#    ce_base.example.class: Sites\CE\BaseBundle\Example

services:
#    ce_base.example:
#        class: %ce_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
