<?php

namespace Sites\Admin\Common\MediatekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function findAllAlphaOrdered($type = "")
    {
        if(!$type){
            return null;
        }
        $qb = $this->createQueryBuilder("d")->where("d.docType=:doctype")->orderBy("d.filename", "ASC")->setParameter("doctype", $type);
        return $qb->getQuery()->getResult();
    }
}
