parameters:
#    beauval_nature_base.example.class: Sites\BeauvalNature\BaseBundle\Example

services:
#    beauval_nature_base.example:
#        class: %beauval_nature_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
