parameters:
#    hameaux_base.example.class: Sites\Hameaux\BaseBundle\Example

services:
#    hameaux_base.example:
#        class: %hameaux_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
