parameters:
#    groupes_base.example.class: Sites\Groupes\BaseBundle\Example

services:
#    groupes_base.example:
#        class: %groupes_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
