parameters:
#    pro_base.example.class: Sites\Pro\BaseBundle\Example

services:
#    pro_base.example:
#        class: %pro_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
