parameters:
#    pagodes_base.example.class: Sites\Pagodes\BaseBundle\Example

services:
#    pagodes_base.example:
#        class: %pagodes_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
