parameters:
#    installer_base.example.class: Sites\Installer\BaseBundle\Example

services:
#    installer_base.example:
#        class: %installer_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
